@echo off
cd /d D:\golang\code\admin
echo Running go mod tidy...
go mod tidy
echo Building...
go build ./cmd/admin
echo Adding files...
git add -A
echo Committing...
git commit -m "fix: 降级Go版本到1.24.0(1.25不存在),修复CI/CD"
echo Pushing to GitHub...
git push
echo Done!
pause
