// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 认证服务
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Admin         *AdminInfo             `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetAdmin() *AdminInfo {
	if x != nil {
		return x.Admin
	}
	return nil
}

type AdminInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfo) Reset() {
	*x = AdminInfo{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfo) ProtoMessage() {}

func (x *AdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfo.ProtoReflect.Descriptor instead.
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AdminInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 管理员管理
type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	RoleIds       []int64                `protobuf:"varint,6,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAdminRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAdminRequest) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type UpdateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	RoleIds       []int64                `protobuf:"varint,6,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAdminRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateAdminRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAdminRequest) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type AdminListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRequest) Reset() {
	*x = AdminListRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRequest) ProtoMessage() {}

func (x *AdminListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRequest.ProtoReflect.Descriptor instead.
func (*AdminListRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type AdminListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminInfo           `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListResponse) Reset() {
	*x = AdminListResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResponse) ProtoMessage() {}

func (x *AdminListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResponse.ProtoReflect.Descriptor instead.
func (*AdminListResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminListResponse) GetAdmins() []*AdminInfo {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *AdminListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 角色管理
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PermissionIds []int64                `protobuf:"varint,5,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleInfo) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type RoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResponse) Reset() {
	*x = RoleListResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResponse) ProtoMessage() {}

func (x *RoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResponse.ProtoReflect.Descriptor instead.
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RoleListResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RoleListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 权限管理
type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type PermissionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionListResponse) Reset() {
	*x = PermissionListResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionListResponse) ProtoMessage() {}

func (x *PermissionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionListResponse.ProtoReflect.Descriptor instead.
func (*PermissionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionListResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 审计日志
type AuditLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	AdminUsername string                 `protobuf:"bytes,3,opt,name=admin_username,json=adminUsername,proto3" json:"admin_username,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	RequestMethod string                 `protobuf:"bytes,6,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	RequestPath   string                 `protobuf:"bytes,7,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	RequestBody   string                 `protobuf:"bytes,8,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody  string                 `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Ip            string                 `protobuf:"bytes,10,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Duration      int64                  `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`
	StatusCode    int32                  `protobuf:"varint,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogInfo) Reset() {
	*x = AuditLogInfo{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogInfo) ProtoMessage() {}

func (x *AuditLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogInfo.ProtoReflect.Descriptor instead.
func (*AuditLogInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AuditLogInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLogInfo) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AuditLogInfo) GetAdminUsername() string {
	if x != nil {
		return x.AdminUsername
	}
	return ""
}

func (x *AuditLogInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLogInfo) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *AuditLogInfo) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *AuditLogInfo) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *AuditLogInfo) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *AuditLogInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditLogInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLogInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AuditLogInfo) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuditLogInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuditLogListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	AdminId       int64                  `protobuf:"varint,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogListRequest) Reset() {
	*x = AuditLogListRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogListRequest) ProtoMessage() {}

func (x *AuditLogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogListRequest.ProtoReflect.Descriptor instead.
func (*AuditLogListRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AuditLogListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AuditLogListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AuditLogListRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AuditLogListRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AuditLogListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLogInfo        `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogListResponse) Reset() {
	*x = AuditLogListResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogListResponse) ProtoMessage() {}

func (x *AuditLogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogListResponse.ProtoReflect.Descriptor instead.
func (*AuditLogListResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AuditLogListResponse) GetLogs() []*AuditLogInfo {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *AuditLogListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 通用响应
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetProfileRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *LogoutRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRequest) Reset() {
	*x = GetAdminRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRequest) ProtoMessage() {}

func (x *GetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ListRolesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AssignPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionIds []int64                `protobuf:"varint,2,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsRequest) Reset() {
	*x = AssignPermissionsRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsRequest) ProtoMessage() {}

func (x *AssignPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *AssignPermissionsRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignPermissionsRequest) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type AssignPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsResponse) Reset() {
	*x = AssignPermissionsResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsResponse) ProtoMessage() {}

func (x *AssignPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *AssignPermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetAuditLogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_admin_v1_admin_proto protoreflect.FileDescriptor

const file_proto_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/admin/v1/admin.proto\x12\badmin.v1\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12)\n" +
	"\x05admin\x18\x02 \x01(\v2\x13.admin.v1.AdminInfoR\x05admin\"\x97\x01\n" +
	"\tAdminInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"L\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x12CreateAdminRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x19\n" +
	"\brole_ids\x18\x06 \x03(\x03R\aroleIds\"\x9f\x01\n" +
	"\x12UpdateAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\brole_ids\x18\x06 \x03(\x03R\aroleIds\"]\n" +
	"\x10AdminListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"V\n" +
	"\x11AdminListResponse\x12+\n" +
	"\x06admins\x18\x01 \x03(\v2\x13.admin.v1.AdminInfoR\x06admins\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"]\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"Y\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8b\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x0epermission_ids\x18\x05 \x03(\x03R\rpermissionIds\"R\n" +
	"\x10RoleListResponse\x12(\n" +
	"\x05roles\x18\x01 \x03(\v2\x12.admin.v1.RoleInfoR\x05roles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x99\x01\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\"T\n" +
	"\x16PermissionListResponse\x12:\n" +
	"\vpermissions\x18\x01 \x03(\v2\x18.admin.v1.PermissionInfoR\vpermissions\"\xb1\x03\n" +
	"\fAuditLogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12%\n" +
	"\x0eadmin_username\x18\x03 \x01(\tR\radminUsername\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12%\n" +
	"\x0erequest_method\x18\x06 \x01(\tR\rrequestMethod\x12!\n" +
	"\frequest_path\x18\a \x01(\tR\vrequestPath\x12!\n" +
	"\frequest_body\x18\b \x01(\tR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\t \x01(\tR\fresponseBody\x12\x0e\n" +
	"\x02ip\x18\n" +
	" \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12\x1a\n" +
	"\bduration\x18\f \x01(\x03R\bduration\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\"y\n" +
	"\x13AuditLogListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\x03R\aadminId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"X\n" +
	"\x14AuditLogListResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.admin.v1.AuditLogInfoR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"D\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\".\n" +
	"\x11GetProfileRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\"*\n" +
	"\rLogoutRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\"D\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fGetAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x10ListRolesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"Z\n" +
	"\x18AssignPermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\x03R\rpermissionIds\"O\n" +
	"\x19AssignPermissionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x18\n" +
	"\x16ListPermissionsRequest\"$\n" +
	"\x12GetAuditLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\x99\x02\n" +
	"\vAuthService\x128\n" +
	"\x05Login\x12\x16.admin.v1.LoginRequest\x1a\x17.admin.v1.LoginResponse\x12>\n" +
	"\n" +
	"GetProfile\x12\x1b.admin.v1.GetProfileRequest\x1a\x13.admin.v1.AdminInfo\x12S\n" +
	"\x0eChangePassword\x12\x1f.admin.v1.ChangePasswordRequest\x1a .admin.v1.ChangePasswordResponse\x12;\n" +
	"\x06Logout\x12\x17.admin.v1.LogoutRequest\x1a\x18.admin.v1.LogoutResponse2\xdc\x02\n" +
	"\fAdminService\x12@\n" +
	"\vCreateAdmin\x12\x1c.admin.v1.CreateAdminRequest\x1a\x13.admin.v1.AdminInfo\x12:\n" +
	"\bGetAdmin\x12\x19.admin.v1.GetAdminRequest\x1a\x13.admin.v1.AdminInfo\x12@\n" +
	"\vUpdateAdmin\x12\x1c.admin.v1.UpdateAdminRequest\x1a\x13.admin.v1.AdminInfo\x12E\n" +
	"\vDeleteAdmin\x12\x1c.admin.v1.DeleteAdminRequest\x1a\x18.admin.v1.DeleteResponse\x12E\n" +
	"\n" +
	"ListAdmins\x12\x1a.admin.v1.AdminListRequest\x1a\x1b.admin.v1.AdminListResponse2\xac\x03\n" +
	"\vRoleService\x12=\n" +
	"\n" +
	"CreateRole\x12\x1b.admin.v1.CreateRoleRequest\x1a\x12.admin.v1.RoleInfo\x127\n" +
	"\aGetRole\x12\x18.admin.v1.GetRoleRequest\x1a\x12.admin.v1.RoleInfo\x12=\n" +
	"\n" +
	"UpdateRole\x12\x1b.admin.v1.UpdateRoleRequest\x1a\x12.admin.v1.RoleInfo\x12C\n" +
	"\n" +
	"DeleteRole\x12\x1b.admin.v1.DeleteRoleRequest\x1a\x18.admin.v1.DeleteResponse\x12C\n" +
	"\tListRoles\x12\x1a.admin.v1.ListRolesRequest\x1a\x1a.admin.v1.RoleListResponse\x12\\\n" +
	"\x11AssignPermissions\x12\".admin.v1.AssignPermissionsRequest\x1a#.admin.v1.AssignPermissionsResponse2j\n" +
	"\x11PermissionService\x12U\n" +
	"\x0fListPermissions\x12 .admin.v1.ListPermissionsRequest\x1a .admin.v1.PermissionListResponse2\xa6\x01\n" +
	"\x0fAuditLogService\x12N\n" +
	"\rListAuditLogs\x12\x1d.admin.v1.AuditLogListRequest\x1a\x1e.admin.v1.AuditLogListResponse\x12C\n" +
	"\vGetAuditLog\x12\x1c.admin.v1.GetAuditLogRequest\x1a\x16.admin.v1.AuditLogInfoB\x1eZ\x1cadmin/proto/admin/v1;adminv1b\x06proto3"

var (
	file_proto_admin_v1_admin_proto_rawDescOnce sync.Once
	file_proto_admin_v1_admin_proto_rawDescData []byte
)

func file_proto_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)))
	})
	return file_proto_admin_v1_admin_proto_rawDescData
}

var file_proto_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_admin_v1_admin_proto_goTypes = []any{
	(*LoginRequest)(nil),              // 0: admin.v1.LoginRequest
	(*LoginResponse)(nil),             // 1: admin.v1.LoginResponse
	(*AdminInfo)(nil),                 // 2: admin.v1.AdminInfo
	(*ChangePasswordRequest)(nil),     // 3: admin.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),    // 4: admin.v1.ChangePasswordResponse
	(*CreateAdminRequest)(nil),        // 5: admin.v1.CreateAdminRequest
	(*UpdateAdminRequest)(nil),        // 6: admin.v1.UpdateAdminRequest
	(*AdminListRequest)(nil),          // 7: admin.v1.AdminListRequest
	(*AdminListResponse)(nil),         // 8: admin.v1.AdminListResponse
	(*CreateRoleRequest)(nil),         // 9: admin.v1.CreateRoleRequest
	(*UpdateRoleRequest)(nil),         // 10: admin.v1.UpdateRoleRequest
	(*RoleInfo)(nil),                  // 11: admin.v1.RoleInfo
	(*RoleListResponse)(nil),          // 12: admin.v1.RoleListResponse
	(*PermissionInfo)(nil),            // 13: admin.v1.PermissionInfo
	(*PermissionListResponse)(nil),    // 14: admin.v1.PermissionListResponse
	(*AuditLogInfo)(nil),              // 15: admin.v1.AuditLogInfo
	(*AuditLogListRequest)(nil),       // 16: admin.v1.AuditLogListRequest
	(*AuditLogListResponse)(nil),      // 17: admin.v1.AuditLogListResponse
	(*Response)(nil),                  // 18: admin.v1.Response
	(*GetProfileRequest)(nil),         // 19: admin.v1.GetProfileRequest
	(*LogoutRequest)(nil),             // 20: admin.v1.LogoutRequest
	(*LogoutResponse)(nil),            // 21: admin.v1.LogoutResponse
	(*GetAdminRequest)(nil),           // 22: admin.v1.GetAdminRequest
	(*DeleteAdminRequest)(nil),        // 23: admin.v1.DeleteAdminRequest
	(*DeleteResponse)(nil),            // 24: admin.v1.DeleteResponse
	(*GetRoleRequest)(nil),            // 25: admin.v1.GetRoleRequest
	(*DeleteRoleRequest)(nil),         // 26: admin.v1.DeleteRoleRequest
	(*ListRolesRequest)(nil),          // 27: admin.v1.ListRolesRequest
	(*AssignPermissionsRequest)(nil),  // 28: admin.v1.AssignPermissionsRequest
	(*AssignPermissionsResponse)(nil), // 29: admin.v1.AssignPermissionsResponse
	(*ListPermissionsRequest)(nil),    // 30: admin.v1.ListPermissionsRequest
	(*GetAuditLogRequest)(nil),        // 31: admin.v1.GetAuditLogRequest
}
var file_proto_admin_v1_admin_proto_depIdxs = []int32{
	2,  // 0: admin.v1.LoginResponse.admin:type_name -> admin.v1.AdminInfo
	2,  // 1: admin.v1.AdminListResponse.admins:type_name -> admin.v1.AdminInfo
	11, // 2: admin.v1.RoleListResponse.roles:type_name -> admin.v1.RoleInfo
	13, // 3: admin.v1.PermissionListResponse.permissions:type_name -> admin.v1.PermissionInfo
	15, // 4: admin.v1.AuditLogListResponse.logs:type_name -> admin.v1.AuditLogInfo
	0,  // 5: admin.v1.AuthService.Login:input_type -> admin.v1.LoginRequest
	19, // 6: admin.v1.AuthService.GetProfile:input_type -> admin.v1.GetProfileRequest
	3,  // 7: admin.v1.AuthService.ChangePassword:input_type -> admin.v1.ChangePasswordRequest
	20, // 8: admin.v1.AuthService.Logout:input_type -> admin.v1.LogoutRequest
	5,  // 9: admin.v1.AdminService.CreateAdmin:input_type -> admin.v1.CreateAdminRequest
	22, // 10: admin.v1.AdminService.GetAdmin:input_type -> admin.v1.GetAdminRequest
	6,  // 11: admin.v1.AdminService.UpdateAdmin:input_type -> admin.v1.UpdateAdminRequest
	23, // 12: admin.v1.AdminService.DeleteAdmin:input_type -> admin.v1.DeleteAdminRequest
	7,  // 13: admin.v1.AdminService.ListAdmins:input_type -> admin.v1.AdminListRequest
	9,  // 14: admin.v1.RoleService.CreateRole:input_type -> admin.v1.CreateRoleRequest
	25, // 15: admin.v1.RoleService.GetRole:input_type -> admin.v1.GetRoleRequest
	10, // 16: admin.v1.RoleService.UpdateRole:input_type -> admin.v1.UpdateRoleRequest
	26, // 17: admin.v1.RoleService.DeleteRole:input_type -> admin.v1.DeleteRoleRequest
	27, // 18: admin.v1.RoleService.ListRoles:input_type -> admin.v1.ListRolesRequest
	28, // 19: admin.v1.RoleService.AssignPermissions:input_type -> admin.v1.AssignPermissionsRequest
	30, // 20: admin.v1.PermissionService.ListPermissions:input_type -> admin.v1.ListPermissionsRequest
	16, // 21: admin.v1.AuditLogService.ListAuditLogs:input_type -> admin.v1.AuditLogListRequest
	31, // 22: admin.v1.AuditLogService.GetAuditLog:input_type -> admin.v1.GetAuditLogRequest
	1,  // 23: admin.v1.AuthService.Login:output_type -> admin.v1.LoginResponse
	2,  // 24: admin.v1.AuthService.GetProfile:output_type -> admin.v1.AdminInfo
	4,  // 25: admin.v1.AuthService.ChangePassword:output_type -> admin.v1.ChangePasswordResponse
	21, // 26: admin.v1.AuthService.Logout:output_type -> admin.v1.LogoutResponse
	2,  // 27: admin.v1.AdminService.CreateAdmin:output_type -> admin.v1.AdminInfo
	2,  // 28: admin.v1.AdminService.GetAdmin:output_type -> admin.v1.AdminInfo
	2,  // 29: admin.v1.AdminService.UpdateAdmin:output_type -> admin.v1.AdminInfo
	24, // 30: admin.v1.AdminService.DeleteAdmin:output_type -> admin.v1.DeleteResponse
	8,  // 31: admin.v1.AdminService.ListAdmins:output_type -> admin.v1.AdminListResponse
	11, // 32: admin.v1.RoleService.CreateRole:output_type -> admin.v1.RoleInfo
	11, // 33: admin.v1.RoleService.GetRole:output_type -> admin.v1.RoleInfo
	11, // 34: admin.v1.RoleService.UpdateRole:output_type -> admin.v1.RoleInfo
	24, // 35: admin.v1.RoleService.DeleteRole:output_type -> admin.v1.DeleteResponse
	12, // 36: admin.v1.RoleService.ListRoles:output_type -> admin.v1.RoleListResponse
	29, // 37: admin.v1.RoleService.AssignPermissions:output_type -> admin.v1.AssignPermissionsResponse
	14, // 38: admin.v1.PermissionService.ListPermissions:output_type -> admin.v1.PermissionListResponse
	17, // 39: admin.v1.AuditLogService.ListAuditLogs:output_type -> admin.v1.AuditLogListResponse
	15, // 40: admin.v1.AuditLogService.GetAuditLog:output_type -> admin.v1.AuditLogInfo
	23, // [23:41] is the sub-list for method output_type
	5,  // [5:23] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_admin_proto_init() }
func file_proto_admin_v1_admin_proto_init() {
	if File_proto_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_admin_proto = out.File
	file_proto_admin_v1_admin_proto_goTypes = nil
	file_proto_admin_v1_admin_proto_depIdxs = nil
}
