// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"admin/internal/biz"
	"admin/internal/conf"
	"admin/internal/data"
	"admin/internal/server"
	"admin/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	serverConf := provideServerConf(bc)
	dataConf := provideDataConf(bc)
	authConf := provideAuthConf(bc)

	// Data 层
	dataData, cleanup, err := data.NewData(dataConf, logger)
	if err != nil {
		return nil, nil, err
	}

	// Repo
	userRepo := data.NewUserRepo(dataData, logger)
	roleRepo := data.NewRoleRepo(dataData, logger)
	permRepo := data.NewPermissionRepo(dataData, logger)
	tenantRepo := data.NewTenantRepo(dataData, logger)
	auditRepo := data.NewAuditRepo(dataData, logger)

	// Biz 层
	userUsecase := biz.NewUserUsecase(userRepo, roleRepo, permRepo, authConf, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, permRepo, logger)
	tenantUsecase := biz.NewTenantUsecase(tenantRepo, logger)

	// Service 层
	authService := service.NewAuthService(userUsecase, logger)
	userService := service.NewUserService(userUsecase, logger)
	roleService := service.NewRoleService(roleUsecase, logger)
	permService := service.NewPermissionService(roleUsecase, logger)
	tenantService := service.NewTenantService(tenantUsecase, logger)
	auditService := service.NewAuditService(auditRepo, logger)

	// Server 层
	grpcServer := server.NewGRPCServer(serverConf, logger, userUsecase, authService, userService, roleService, permService, tenantService, auditService)
	httpServer := server.NewHTTPServer(serverConf, logger)

	// App
	app := newApp(logger, grpcServer, httpServer)

	return app, func() {
		cleanup()
	}, nil
}
